display_name: FlClash
package_name: FlClash
maintainer:
  name: vulcanen
  email: vulcanen@users.noreply.github.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash

categories:
  - Network

startup_notify: true